name: Generate Rainbow Grid

on:
  schedule:
    - cron: "0 0 * * *"   # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:       # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Rainbow Grid Animation
        uses: Platane/snk@v3
        with:
          github_user_name: viranarullita
          outputs: dist/rainbow-grid.svg
          palette: "pink"   # ðŸŒ¸ pakai warna pink pastel

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
